name    'gajdaw-php5'
version '0.1.3'
source 'git://github.com/pro-vagrant/puppet-php5.git'
author ' Włodzimierz Gajda'
license 'MIT'
summary 'The module to install php5'
description 'The module to install php5'
project_page 'https://github.com/pro-vagrant/puppet-php5'
